name: Build-and-Push-Image
on:
  push:
    branches:
      - master
jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: rishithamarri
      IMAGE_NAME: express-docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "GITHUB_BRANCH= $(echo $GITHUB_REF_NAME-$GITHUB-SHA)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $REPO_NAME/$IMAGE_NAME:$GITHUB_REF_NAME-$GITHUB-SHA .

      - name: Push Image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username $REPO_NAME --password-stdin
          docker push $REPO_NAME/$IMAGE_NAME:$GITHUB_REF_NAME-$GITHUB-SHA

      - name: Manifet file
        run: |

          git clone https://${{ secrets.AWS_GITHUB_USER }}:${{ secrets.AWS_GITHUB_TOKEN }}@github.com/rishitha1007/Gitops_expressjs
          ls

          cd Gitops_expressjs

          git config user.name "$GITHUB_ACTOR"

          git config user.email "$GITHUB_ACTOR@wohlig.com

          yq e '.spec.template.spec.containers[0].image = "rishithamarri/express-docker:${{ env.GITHUB_BRANCH }}"' -i deployments/express.yml


          git add .

          git commit -m "updating newer image"

          git push --set-upstream origin main\
