name: Build-and-Push-Image
on:
  push:
    branches:
      - master
jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: rishithamarri
      IMAGE_NAME: express-docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "GITHUB_BRANCH= $(echo $GITHUB_REF_NAME-$GITHUB-SHA)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $REPO_NAME/$IMAGE_NAME:$GITHUB_REF_NAME-$GITHUB-SHA .

      - name: Push Image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username $REPO_NAME --password-stdin
          docker push $REPO_NAME/$IMAGE_NAME:$GITHUB_REF_NAME-$GITHUB-SHA
          
